# Generated by Django 3.0.8 on 2020-07-20 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_name', models.CharField(max_length=255)),
                ('payloads', models.TextField()),
                ('received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
