# Generated by Django 3.0.8 on 2020-07-20 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_webhook_sender_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='received',
            new_name='received_at',
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Event local ID'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='sender_login',
            field=models.CharField(max_length=255, verbose_name='Event by'),
        ),
    ]
