# Generated by Django 3.0.8 on 2020-07-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBuildRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_on_event', models.CharField(max_length=255)),
                ('build_started_at', models.DateTimeField(auto_now_add=True)),
                ('build_status', models.CharField(choices=[('Build started', 'Build started'), ('Build failed', 'Build failed'), ('Build finished', 'Build finished')], max_length=255)),
                ('return_code', models.IntegerField()),
                ('build_logs', models.TextField()),
            ],
        ),
    ]
