# Generated by Django 3.0.8 on 2020-07-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_build', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbuildrecord',
            name='repository_name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appbuildrecord',
            name='repository_owner_name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
